"""Phase 5: profiles and user_settings

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01

Autogenerated, reviewed by hand. Phase 0 §5.1 (1:1 with users, user_id is the PK).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column(
            "links",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("timezone", sa.Text(), server_default="Asia/Kolkata", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_profiles_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_profiles")),
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "threshold_use_master", sa.SmallInteger(), server_default=sa.text("85"), nullable=False
        ),
        sa.Column(
            "threshold_tailor", sa.SmallInteger(), server_default=sa.text("65"), nullable=False
        ),
        sa.Column(
            "score_weights",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                """'{"skills": 40, "experience": 25, "technology": 20, """
                """"education": 10, "location": 5}'::jsonb"""
            ),
            nullable=False,
        ),
        sa.Column(
            "auto_analyze_new_jobs", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "daily_send_cap", sa.SmallInteger(), server_default=sa.text("25"), nullable=False
        ),
        sa.Column(
            "send_interval_seconds", sa.Integer(), server_default=sa.text("90"), nullable=False
        ),
        sa.Column(
            "recipient_cooldown_days",
            sa.SmallInteger(),
            server_default=sa.text("30"),
            nullable=False,
        ),
        sa.Column("follow_up_days", sa.SmallInteger(), server_default=sa.text("7"), nullable=False),
        sa.Column(
            "no_response_days", sa.SmallInteger(), server_default=sa.text("21"), nullable=False
        ),
        sa.Column(
            "linkedin_source_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "automation_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "automation_min_score", sa.SmallInteger(), server_default=sa.text("70"), nullable=False
        ),
        sa.Column(
            "llm_models",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "monthly_ai_budget_usd",
            sa.Numeric(precision=8, scale=2),
            server_default=sa.text("5.00"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "automation_min_score BETWEEN 0 AND 100",
            name=op.f("ck_user_settings_automation_min_score_range"),
        ),
        sa.CheckConstraint(
            "daily_send_cap >= 0 AND send_interval_seconds >= 0 AND recipient_cooldown_days >= 0 "
            "AND follow_up_days >= 0 AND no_response_days >= 0 AND monthly_ai_budget_usd >= 0",
            name=op.f("ck_user_settings_non_negative"),
        ),
        sa.CheckConstraint(
            "threshold_tailor < threshold_use_master", name=op.f("ck_user_settings_threshold_order")
        ),
        sa.CheckConstraint(
            "threshold_use_master BETWEEN 0 AND 100 AND threshold_tailor BETWEEN 0 AND 100",
            name=op.f("ck_user_settings_threshold_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_settings_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_settings")
    op.drop_table("profiles")
    # ### end Alembic commands ###
