"""Phase 7: resumes, resume_versions, resume_ats_reports

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-02

Autogenerated, reviewed by hand (Phase 0 §5.2):
- one named CHECK per enum column,
- resumes.active_version_id ↔ resume_versions is circular → FK added after both tables,
- resume_versions.job_id gets its FK to jobs in Phase 8.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

JSONB = postgresql.JSONB(astext_type=sa.Text())


def _id() -> sa.Column:
    return sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False)


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    ]


def upgrade() -> None:
    op.create_table(
        "resumes",
        _id(),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), server_default="Master resume", nullable=False),
        sa.Column("active_version_id", sa.UUID(), nullable=True),
        *_timestamps(),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_resumes_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
    )
    op.create_index("ix_resumes_user_id", "resumes", ["user_id"])

    op.create_table(
        "resume_versions",
        _id(),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("derived_from_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("file_key", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("parsed", JSONB, nullable=True),
        sa.Column("parse_status", sa.String(length=7), server_default="pending", nullable=False),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("content_html", sa.Text(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(
            "kind IN ('master', 'improved', 'tailored')",
            name=op.f("ck_resume_versions_resume_kind"),
        ),
        sa.CheckConstraint(
            "parse_status IN ('pending', 'parsed', 'failed')",
            name=op.f("ck_resume_versions_parse_status"),
        ),
        sa.CheckConstraint(
            "(kind = 'tailored') = (job_id IS NOT NULL)",
            name=op.f("ck_resume_versions_tailored_has_job"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_resume_versions_user_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
            name=op.f("fk_resume_versions_resume_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["derived_from_id"],
            ["resume_versions.id"],
            name=op.f("fk_resume_versions_derived_from_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume_versions")),
        sa.UniqueConstraint(
            "resume_id", "version_no", name=op.f("uq_resume_versions_resume_id_version_no")
        ),
    )
    op.create_index("ix_resume_versions_user_id", "resume_versions", ["user_id"])

    # Circular reference: added once both tables exist.
    op.create_foreign_key(
        op.f("fk_resumes_active_version_id"),
        "resumes",
        "resume_versions",
        ["active_version_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_table(
        "resume_ats_reports",
        _id(),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("resume_version_id", sa.UUID(), nullable=False),
        sa.Column("ats_score", sa.SmallInteger(), nullable=False),
        sa.Column("section_scores", JSONB, nullable=False),
        sa.Column("strengths", JSONB, nullable=False),
        sa.Column("missing_skills", JSONB, nullable=False),
        sa.Column("top_roles", JSONB, nullable=False),
        sa.Column("suggestions", JSONB, nullable=False),
        sa.Column("linkedin_summary", JSONB, nullable=True),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        *_timestamps(),
        sa.CheckConstraint(
            "ats_score BETWEEN 0 AND 100", name=op.f("ck_resume_ats_reports_ats_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_resume_ats_reports_user_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resume_version_id"],
            ["resume_versions.id"],
            name=op.f("fk_resume_ats_reports_resume_version_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume_ats_reports")),
    )
    op.create_index("ix_resume_ats_reports_user_id", "resume_ats_reports", ["user_id"])
    op.create_index(
        "ix_resume_ats_reports_resume_version_id", "resume_ats_reports", ["resume_version_id"]
    )


def downgrade() -> None:
    op.drop_index("ix_resume_ats_reports_resume_version_id", table_name="resume_ats_reports")
    op.drop_index("ix_resume_ats_reports_user_id", table_name="resume_ats_reports")
    op.drop_table("resume_ats_reports")
    op.drop_constraint(op.f("fk_resumes_active_version_id"), "resumes", type_="foreignkey")
    op.drop_index("ix_resume_versions_user_id", table_name="resume_versions")
    op.drop_table("resume_versions")
    op.drop_index("ix_resumes_user_id", table_name="resumes")
    op.drop_table("resumes")
