"""Phase 8: jobs, user_jobs, saved_searches, job_search_runs, job_search_results

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-02

Autogenerated, reviewed by hand (Phase 0 §5.3):
- one named CHECK per enum column,
- adds the resume_versions.job_id → jobs FK promised in 0005.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

JSONB = postgresql.JSONB(astext_type=sa.Text())
SOURCES = "('jsearch', 'manual', 'legacy_sheet')"


def _id() -> sa.Column:
    return sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False)


def _now(name: str, nullable: bool = False) -> sa.Column:
    return sa.Column(
        name, sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=nullable
    )


def _timestamps() -> list[sa.Column]:
    return [_now("created_at"), _now("updated_at")]


def _user_fk(table: str) -> sa.ForeignKeyConstraint:
    return sa.ForeignKeyConstraint(
        ["user_id"], ["users.id"], name=op.f(f"fk_{table}_user_id"), ondelete="CASCADE"
    )


def upgrade() -> None:
    op.create_table(
        "jobs",
        _id(),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=7), server_default="public", nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("company", sa.Text(), nullable=False),
        sa.Column("company_domain", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("is_remote", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("employment_type", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_quality", sa.String(length=8), nullable=False),
        sa.Column("apply_url", sa.Text(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column("raw", JSONB, nullable=True),
        sa.Column("dedupe_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=9), server_default="active", nullable=False),
        sa.Column("duplicate_of_id", sa.UUID(), nullable=True),
        _now("first_seen_at"),
        _now("last_seen_at"),
        *_timestamps(),
        sa.CheckConstraint(f"source IN {SOURCES}", name=op.f("ck_jobs_job_source")),
        sa.CheckConstraint(
            "visibility IN ('public', 'private')", name=op.f("ck_jobs_job_visibility")
        ),
        sa.CheckConstraint(
            "description_quality IN ('complete', 'partial', 'missing')",
            name=op.f("ck_jobs_description_quality"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'expired', 'duplicate')", name=op.f("ck_jobs_job_status")
        ),
        sa.CheckConstraint(
            "(visibility = 'private') = (created_by_user_id IS NOT NULL)",
            name=op.f("ck_jobs_private_has_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_jobs_created_by_user_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_id"],
            ["jobs.id"],
            name=op.f("fk_jobs_duplicate_of_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("source", "external_id", name=op.f("uq_jobs_source_external_id")),
    )
    op.create_index("ix_jobs_dedupe_hash", "jobs", ["dedupe_hash"])
    op.create_index("ix_jobs_posted_at", "jobs", ["posted_at"])

    op.create_table(
        "user_jobs",
        _id(),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=8), server_default="new", nullable=False),
        sa.Column("description_override", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        _now("first_found_at"),
        *_timestamps(),
        sa.CheckConstraint(
            "state IN ('new', 'saved', 'analyzed', 'skipped', 'archived')",
            name=op.f("ck_user_jobs_user_job_state"),
        ),
        _user_fk("user_jobs"),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_user_jobs_job_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_jobs")),
        sa.UniqueConstraint("user_id", "job_id", name=op.f("uq_user_jobs_user_id_job_id")),
    )
    op.create_index("ix_user_jobs_user_id_state", "user_jobs", ["user_id", "state"])

    op.create_table(
        "saved_searches",
        _id(),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("keywords", sa.Text(), nullable=False),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("experience", sa.Text(), nullable=True),
        sa.Column("remote_only", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("country", sa.String(length=2), server_default="in", nullable=False),
        sa.Column("schedule_cron", sa.Text(), server_default="0 8 * * *", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        _user_fk("saved_searches"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_searches")),
    )
    op.create_index("ix_saved_searches_user_id", "saved_searches", ["user_id"])

    op.create_table(
        "job_search_runs",
        _id(),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("saved_search_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("query", JSONB, nullable=False),
        sa.Column("status", sa.String(length=9), server_default="queued", nullable=False),
        sa.Column("results_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("new_jobs_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.CheckConstraint(f"source IN {SOURCES}", name=op.f("ck_job_search_runs_job_source")),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed')",
            name=op.f("ck_job_search_runs_search_run_status"),
        ),
        _user_fk("job_search_runs"),
        sa.ForeignKeyConstraint(
            ["saved_search_id"],
            ["saved_searches.id"],
            name=op.f("fk_job_search_runs_saved_search_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_job_search_runs_task_id"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_search_runs")),
    )
    op.create_index(
        "ix_job_search_runs_user_id_created_at", "job_search_runs", ["user_id", "created_at"]
    )

    op.create_table(
        "job_search_results",
        sa.Column("search_run_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        _now("created_at"),
        sa.ForeignKeyConstraint(
            ["search_run_id"],
            ["job_search_runs.id"],
            name=op.f("fk_job_search_results_search_run_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_search_results_job_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("search_run_id", "job_id", name=op.f("pk_job_search_results")),
    )

    op.create_foreign_key(
        op.f("fk_resume_versions_job_id"),
        "resume_versions",
        "jobs",
        ["job_id"],
        ["id"],
        ondelete="RESTRICT",
    )


def downgrade() -> None:
    op.drop_constraint(op.f("fk_resume_versions_job_id"), "resume_versions", type_="foreignkey")
    op.drop_table("job_search_results")
    op.drop_index("ix_job_search_runs_user_id_created_at", table_name="job_search_runs")
    op.drop_table("job_search_runs")
    op.drop_index("ix_saved_searches_user_id", table_name="saved_searches")
    op.drop_table("saved_searches")
    op.drop_index("ix_user_jobs_user_id_state", table_name="user_jobs")
    op.drop_table("user_jobs")
    op.drop_index("ix_jobs_posted_at", table_name="jobs")
    op.drop_index("ix_jobs_dedupe_hash", table_name="jobs")
    op.drop_table("jobs")
